### ISSUE TITLE
orange alert difference between develop and build

### ISSUE THREAD

**Issue by huphtur** [cossssmin/gridsome-starter-bleda#2]
on [this page](https://gridsome-starter-bleda.netlify.com/jeffsum-lorem-ipsum-generator/), the alert component looks different between build:

![build](https://user-images.githubusercontent.com/469438/54063257-3b8af700-41c0-11e9-9b22-223803c1d444.png)

and develop:

![develop](https://user-images.githubusercontent.com/469438/54063259-40e84180-41c0-11e9-921e-896fdbce8155.png)

any idea what happened there?

**Comment by cossssmin** [comment]
Indeed. What happens is that the color classes are dynamically built in that alert component based on a computed prop, and PurgeCSS works by matching strings. 

So when purging classes, instead of seeing `text-orange-darker` for example, it sees something like `text-${color}-darker`. So it purges that class, thinking it’s unused. 

The only way around that is to pass the entire class to the component - I’ll have it updated over the weekend.
